name: Scheduled Scraping

on:
  schedule:
    # Run at 6:00, 12:00, and 18:00 UTC every day
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: latest
        
    - name: Display Chrome and ChromeDriver versions
      run: |
        echo "Chrome version:"
        google-chrome --version
        echo "ChromeDriver version:"
        chromedriver --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scrapers
      run: |
        echo "Starting scrapers..."
        for script in scraper_*.py; do
          if [ -f "$script" ]; then
            echo "Running $script..."
            python "$script" || echo "Warning: $script failed to run"
          else
            echo "Warning: $script not found"
          fi
        done
        
    - name: Commit and push if changes
      run: |
        echo "Checking for changes..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Update scraped data" -a || exit 0
          echo "Pushing changes..."
          git push
        fi 