name: Scheduled Scraping

on:
  schedule:
    # Run at 6:00, 12:00, and 18:00 UTC every day
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Install required packages
        sudo apt-get update
        sudo apt-get install -y wget gnupg2 unzip
        
        # Add Google Chrome repository
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        
        # Install Chrome
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Get Chrome version and download matching ChromeDriver
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        echo "Chrome version: $CHROME_VERSION"
        
        # Download and install ChromeDriver
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip"
        unzip -q chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Verify installations
        echo "Chrome version:"
        google-chrome --version
        echo "ChromeDriver version:"
        chromedriver --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Convert notebooks to Python scripts
      run: |
        echo "Converting notebooks to Python scripts..."
        for notebook in scraper_*.ipynb; do
          if [ -s "$notebook" ]; then
            echo "Converting $notebook..."
            jupyter nbconvert --to python "$notebook" || echo "Failed to convert $notebook"
          fi
        done
        
    - name: Run scrapers
      run: |
        echo "Starting scrapers..."
        for script in scraper_*.py; do
          if [ -f "$script" ]; then
            echo "Running $script..."
            python "$script" || echo "Warning: $script failed to run"
          else
            echo "Warning: $script not found"
          fi
        done
        
    - name: Commit and push if changes
      run: |
        echo "Checking for changes..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Update scraped data" -a || exit 0
          echo "Pushing changes..."
          git push 