name: Scheduled Scraping

on:
  schedule:
    # This will run every day at 2 AM UTC
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert pandas requests beautifulsoup4
        
    - name: Convert notebooks to Python scripts
      run: |
        jupyter nbconvert --to python scraper_*.ipynb
        
    - name: Run scrapers
      run: |
        python scraper_koepel.py
        python scraper_coolcharm.py
        python scraper_rite.py
        python scraper_rowreformer.py
        python yoko.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data/
        git commit -m "Update scraped data" -a || exit 0
        git push 