name: Scheduled Scraping

on:
  schedule:
    # Run at 6:00, 12:00, and 18:00 UTC every day
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  # Allow manual triggering
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        echo "Chrome version: $CHROME_VERSION"
        
        # Download and install ChromeDriver
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.92/linux64/chromedriver-linux64.zip"
        unzip -q chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Verify installation
        echo "ChromeDriver version:"
        chromedriver --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Convert notebooks to Python scripts
      run: |
        echo "Converting notebooks to Python scripts..."
        for notebook in *.ipynb; do
          if [ -f "$notebook" ]; then
            echo "Converting $notebook..."
            jupyter nbconvert --to python "$notebook"
          fi
        done
        
    - name: Run scrapers
      run: |
        echo "Starting scrapers..."
        for script in *.py; do
          if [ -f "$script" ]; then
            echo "Running $script..."
            python "$script" || echo "Warning: $script failed to run"
          fi
        done
        
    - name: Commit and push if changes
      run: |
        echo "Checking for changes..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Update scraped data" -a || exit 0
          echo "Pushing changes..."
          git push
        fi 